export { type ClaudeCodeConfig, createClaudeCodeChannel, type TaskResult } from './claude-code'
export { createCLIChannel } from './cli'
export { createDiscordChannel, type DiscordConfig } from './discord'
export { createMatrixChannel, type MatrixConfig } from './matrix'
export { createTelegramChannel, type TelegramConfig } from './telegram'
export type { Channel, ChatChannel, OutboundChannel } from './types'
export { createXMPPChannel, type XMPPConfig } from './xmpp'
