import type { RuntimeConfig } from '../config'
import type { ConversationStore } from '../conversation'
import type { MemoryManager } from '../memory'
import { createLlamaCppTokenizer } from '../providers/llamacpp-tokenizer'
import type {
  ChatMessage,
  ChatResponse,
  LLMProvider,
  ThinkingConfig,
  Tokenizer,
} from '../providers/types'
import type { ToolExecutor } from '../tools'
import { hasStrandedToolCall, stripStrandedToolCalls } from '../tools/format'
import { trace } from '../tracking/traces'
import type { TranscriptLogger } from '../tracking/transcript'
import { log } from '../util/logger'
import { runAutoExtraction } from './background'
import { slotFor } from './cache-slots'
import { chatWithContextWindow } from './chat'
import { CompactionScheduler } from './compaction'
import {
  type AgentContext,
  addMessage,
  createAgentContext,
  type SystemPromptOptions,
} from './context'
import type { AgentEventHandler } from './events'
import { ConversationHistory } from './history'
import {
  checkpointNudge,
  DEFAULT_VALIDATION_FEEDBACK,
  interjectionNudge,
  MAX_TURNS_SUMMARY_NUDGE,
  planningModePrompt,
  validationFailedNudge,
  wrapupNudge,
} from './nudges'
import { injectRecalledMemory } from './recall'
import { attemptRecovery, resolveRecoveryCaps } from './recovery'
import { createRunState } from './run-state'
import type { SessionMutex } from './session-mutex'
import { isReasoningLooping, SpiralDetector, turnSignature } from './spiral-guard'
import { type ContextStatus, computeContextStatus } from './status'
import { reportTokenBudget, TokenBudgetTracker } from './token-budget'
import { runToolCalls } from './tool-runner'
import type { AgentLoopDeps, AgentLoopOptions, AgentResponse } from './types'

/**
 * Hard turn ceiling for an unbounded run. Not a normal stop — the failure detectors and the
 * agent's own conclusion end a healthy run long before this. Reaching it means every detector
 * failed to catch a runaway, which is logged as an error. High enough to never bound real work.
 */
const UNBOUNDED_SAFETY_CEILING = 10_000

/**
 * Context utilization at which a consolidation break fires regardless of the turn interval —
 * the point where compaction is imminent, so durable capture must happen now. Matches the
 * /context "getting tight" threshold so the two agree.
 */
const CONTEXT_BREAK_THRESHOLD = 0.8

export type AgentFactory = (sessionId: string) => AgentLoop

export class AgentLoop {
  private config: RuntimeConfig
  private toolExecutor: ToolExecutor
  private localProvider: LLMProvider
  private auxProvider: LLMProvider
  private memory: MemoryManager | null
  private context: AgentContext
  private tokenizer: Tokenizer
  private conversationStore: ConversationStore | null
  private transcript: TranscriptLogger | null
  private promptOptions: SystemPromptOptions
  private mutex: SessionMutex | null
  private history: ConversationHistory
  private compactor = new CompactionScheduler()
  /**
   * The in-flight run, if any — the handle interrupt() and inject() act through. One run at
   * a time per loop instance is already the contract everywhere (the API chains requests per
   * session; the CLI and runner are single-run by construction), so a single slot suffices.
   */
  private activeRun: { controller: AbortController; pendingInjections: string[] } | null = null

  constructor(deps: AgentLoopDeps) {
    this.config = deps.config
    this.toolExecutor = deps.toolExecutor
    this.localProvider = deps.localProvider
    // Side work runs on the auxiliary model when configured. It does not need the operator
    // model's capability, and running it there costs a slot and competes for context: the
    // 396-character summary that wiped a research task was generated by the 27B mid-task.
    this.auxProvider = deps.auxProvider ?? deps.localProvider
    this.memory = deps.memory ?? null
    this.conversationStore = deps.conversationStore ?? null
    this.mutex = deps.sessionMutex ?? null
    this.transcript = deps.transcript ?? null
    this.promptOptions = { skills: deps.skills, additionalContext: deps.additionalContext }
    this.context = createAgentContext(deps.config, deps.sessionId, this.promptOptions)
    this.tokenizer = createLlamaCppTokenizer(deps.config.local.endpoint)
    this.history = new ConversationHistory(this.conversationStore, deps.sessionId)
    this.history.hydrate(this.context)
  }

  /**
   * KV cache slot for this session, from the shared registry (see ./cache-slots.ts).
   * Local servers with per-slot prefix caching reuse the context this conversation already
   * prefilled — the difference between ~60 s and <1 s to first token on a continuation turn.
   */
  private cacheSlot(): number | undefined {
    return slotFor(this.context.sessionId, this.config.local.cacheSlots)
  }

  async run(userMessage: string, options: AgentLoopOptions = {}): Promise<AgentResponse> {
    // The mutex guards tool execution only (see SessionMutex): inference runs outside it
    // so concurrent sessions can be batched by the local server. Wrapping the whole run
    // here would serialize every entry point again.
    return this.doRun(userMessage, options)
  }

  /** Run a tool phase under the shared-state lock. */
  private async exclusive<T>(fn: () => Promise<T>): Promise<T> {
    return this.mutex ? this.mutex.run(fn) : fn()
  }

  /**
   * Abort the in-flight run, if any. The run ends through the same signal path as every
   * other abort (timeout, shutdown), including a stuck inference — the provider's fetch is
   * cancelled. Returns false when nothing is running.
   */
  interrupt(): boolean {
    if (!this.activeRun) return false
    this.activeRun.controller.abort('interrupt')
    return true
  }

  /**
   * Queue a message into the in-flight run. It is delivered at the top of the next turn —
   * never spliced into the middle of one, where a user message between an assistant tool
   * call and its tool results would corrupt the transcript the model sees. Returns false
   * when nothing is running (callers should send a normal chat message instead).
   */
  inject(message: string): boolean {
    if (!this.activeRun) return false
    this.activeRun.pendingInjections.push(message)
    return true
  }

  isRunning(): boolean {
    return this.activeRun !== null
  }

  private async doRun(userMessage: string, options: AgentLoopOptions): Promise<AgentResponse> {
    await this.compactor.drain()

    const { events, planningMode } = options
    // Every run gets its own controller so interrupt() can end it without the caller having
    // passed a signal. An external signal (task timeout, shutdown) forwards into it, keeping
    // one signal — `signal` below — as the single thing the loop body watches.
    const runController = new AbortController()
    const externalSignal = options.signal
    const forwardAbort = () => runController.abort(externalSignal?.reason ?? 'external')
    if (externalSignal) {
      if (externalSignal.aborted) forwardAbort()
      else externalSignal.addEventListener('abort', forwardAbort, { once: true })
    }
    const signal = runController.signal
    this.activeRun = { controller: runController, pendingInjections: [] }
    // Unbounded runs replace the turn cap with a far-off safety ceiling: the run is meant to
    // end on a mechanical failure, a semantic report, or a human — not an artificial count.
    // The ceiling is a backstop only; hitting it means a detector that should have fired
    // didn't, which is a bug, not a normal exit. See docs/autonomy-loop.md.
    const maxTurns = options.unbounded ? UNBOUNDED_SAFETY_CEILING : (options.maxTurns ?? 10)
    const turnStartedAt = Date.now()

    const thinking: ThinkingConfig | undefined =
      options.thinking ??
      (this.config.thinking.level !== 'off'
        ? { level: this.config.thinking.level, budgetTokens: this.config.thinking.budgetTokens }
        : undefined)

    const userContent = planningMode ? planningModePrompt(userMessage) : userMessage

    this.transcript?.turnStart(this.context.sessionId, userMessage)
    // Attached images ride the same message as the text, in the content-part shape the
    // provider already renders for the screenshot tool.
    if (options.images?.length) {
      addMessage(this.context, {
        role: 'user',
        content: [
          { type: 'text', text: userContent },
          ...options.images.map((url) => ({ type: 'image_url' as const, image_url: { url } })),
        ],
      })
    } else {
      addMessage(this.context, { role: 'user', content: userContent })
    }

    await injectRecalledMemory({
      userMessage,
      context: this.context,
      memory: this.memory,
      config: this.config,
      history: this.history,
      transcript: this.transcript,
    })

    // Every counter and flag scoped to this run — the loop's state machine, made explicit.
    const state = createRunState()
    const recoveryCaps = resolveRecoveryCaps(this.config.recovery)
    const totalUsage = { input_tokens: 0, output_tokens: 0 }
    let finalContent = ''
    const provider = this.localProvider

    const budgetTracker = new TokenBudgetTracker(this.config.local.contextLength)

    let lastThinking: string | undefined
    let isPlanning = !!planningMode
    const seenToolCalls = new Set<string>()
    const spiral = new SpiralDetector()
    // Turns between consolidation breaks (0 = off). Per-run option wins over config default.
    const consolidationInterval =
      options.consolidationInterval ?? this.config.conversation.consolidationInterval ?? 0
    // Wall-clock wrap-up: warn once as the hard deadline (a task timeout) nears, so the agent
    // winds down and checkpoints on its own instead of being killed mid-inference.
    const deadline = options.deadline
    const wrapupMarginMs = options.wrapupMarginMs ?? 7 * 60_000

    // Persistence and transcript closure run in `finally` so a provider error
    // mid-run doesn't lose the user message and tool activity already in context.
    try {
      while (state.turns < maxTurns) {
        if (signal?.aborted) {
          log.info('agent', 'Agent run aborted by signal')
          break
        }

        state.turns++

        // Operator interjections queued by inject() land here — at a turn boundary, after
        // any tool results are already paired with their calls — as ordinary user messages.
        if (this.activeRun && this.activeRun.pendingInjections.length > 0) {
          for (const injected of this.activeRun.pendingInjections.splice(0)) {
            addMessage(this.context, { role: 'user', content: interjectionNudge(injected) })
          }
        }

        // Consolidation break: inject one checkpoint turn telling the agent to externalize
        // what it has learned before continuing. It keeps the durable record current (so an
        // interruption loses nothing), breaks a reasoning rut by forcing an act-and-continue,
        // and — most importantly — ensures everything is on disk BEFORE compaction trims the
        // conversation, so nothing real is ever lost to summarization. See docs/autonomy-loop.md.
        //
        // Two triggers, one mechanism. The interval trigger is a steady rhythm; the context
        // trigger fires when the window is filling and compaction is imminent — which is exactly
        // the moment durable capture matters most. The context trigger is rate-limited to one
        // per interval window so a sustained-high context does not nag every turn.
        if (consolidationInterval > 0) {
          const onInterval = state.turns > 1 && (state.turns - 1) % consolidationInterval === 0
          const utilization = state.lastInputTokens / Math.max(1, this.config.local.contextLength)
          const contextPressed =
            utilization >= CONTEXT_BREAK_THRESHOLD &&
            state.turns - state.lastContextBreakTurn >= consolidationInterval
          if (onInterval || contextPressed) {
            if (contextPressed) state.lastContextBreakTurn = state.turns
            addMessage(this.context, { role: 'user', content: checkpointNudge(contextPressed) })
          }
        }

        // Wall-clock wrap-up: as the run nears its hard deadline, tell the agent once to stop
        // starting new work, write its notes, and conclude. This turns the task-timeout
        // guillotine into a self-directed wind-down — the time-based sibling of the
        // consolidation break, keeping the wall-clock limit consistent with the loop's
        // "pause and capture" rhythm rather than killing a turn mid-thought. See
        // docs/autonomy-loop.md.
        if (deadline && !state.wrapupWarned && Date.now() >= deadline - wrapupMarginMs) {
          state.wrapupWarned = true
          const minsLeft = Math.max(1, Math.round((deadline - Date.now()) / 60_000))
          addMessage(this.context, { role: 'user', content: wrapupNudge(minsLeft) })
        }

        const tools = isPlanning ? [] : this.toolExecutor.getDefinitions()

        let response: ChatResponse
        const inferenceStart = Date.now()
        try {
          const result = await chatWithContextWindow({
            provider,
            systemPrompt: this.context.systemPrompt,
            messages: this.context.messages,
            conversationSummary: this.context.conversationSummary,
            tools,
            contextLength: this.config.local.contextLength,
            tokenizer: this.tokenizer,
            onToken: events?.onToken,
            onThinkingToken: events?.onThinkingToken,
            thinking,
            signal,
            cacheSlot: this.cacheSlot(),
          })
          response = result.response

          if (result.wasTrimmed && this.config.conversation.contextCompaction) {
            this.scheduleCompaction(result.droppedMessages)
          }
        } catch (error) {
          if (signal?.aborted) {
            log.info('agent', 'Agent run aborted during inference')
            break
          }
          const err = error instanceof Error ? error : new Error(String(error))
          events?.onError?.(err)
          throw error
        }
        const inferenceDuration = Date.now() - inferenceStart

        // Input tokens are the whole prompt this turn — the running measure of context fill,
        // used by the context-pressure consolidation trigger next iteration.
        state.lastInputTokens = response.usage.input_tokens
        totalUsage.input_tokens += response.usage.input_tokens
        totalUsage.output_tokens += response.usage.output_tokens

        this.transcript?.inference(this.context.sessionId, {
          provider: provider.name,
          input_tokens: response.usage.input_tokens,
          output_tokens: response.usage.output_tokens,
          duration_ms: inferenceDuration,
          has_tool_calls: (response.tool_calls?.length ?? 0) > 0,
        })

        // Full-fidelity turn trace: thinking is otherwise streamed and dropped, and it is
        // the single most useful artifact when reconstructing why a run went sideways.
        trace({
          session: this.context.sessionId,
          kind: 'turn',
          name: response.model ?? provider.name,
          tokensIn: response.usage.input_tokens,
          tokensOut: response.usage.output_tokens,
          durationMs: inferenceDuration,
          payload: {
            content: response.content ?? '',
            thinking: response.thinking ?? '',
            tool_calls: (response.tool_calls ?? []).map((c) => c.name).join(','),
          },
        })

        reportTokenBudget({
          tracker: budgetTracker,
          inputTokens: response.usage.input_tokens,
          outputTokens: response.usage.output_tokens,
          context: this.context,
          transcript: this.transcript,
          events,
        })

        if (response.thinking) {
          lastThinking = response.thinking
          events?.onThinking?.(response.thinking)
        }

        // Thinking death spiral within a single inference: the reasoning block loops on the
        // same fragment instead of converging. This never escapes one turn to be counted
        // across turns, so the cross-turn detector below cannot see it.
        if (isReasoningLooping(response.thinking)) {
          log.warn(
            'agent',
            `Reasoning is looping within a turn (turn ${state.turns}) — aborting run`,
          )
          finalContent =
            `${state.accumulatedContent + response.content}\n\n` +
            `[Run aborted: the agent's reasoning entered a repetition loop.]`
          addMessage(this.context, { role: 'assistant', content: response.content })
          break
        }

        if (response.tool_calls && response.tool_calls.length > 0) {
          // Cross-turn spiral: the model has now issued the same call with the same arguments
          // (and reasoned the same way) enough times in a row that it is looping, not working
          // (the RE case: reissuing the same execute_command). Break before running it again
          // and burning the budget. Only tool-executing turns are counted here -- the stranded,
          // continuation and empty paths return identical responses by design and are already
          // bounded by their own caps.
          if (
            spiral.record(turnSignature(response.content, response.tool_calls, response.thinking))
          ) {
            log.warn(
              'agent',
              `Agent is repeating the same action across turns (turn ${state.turns}) — aborting run`,
            )
            finalContent =
              `${state.accumulatedContent + response.content}\n\n` +
              `[Run aborted: the agent began repeating the same action without progress.]`
            addMessage(this.context, { role: 'assistant', content: response.content })
            break
          }

          const toolOutcome = await this.exclusive(() =>
            runToolCalls({
              response,
              context: this.context,
              executor: this.toolExecutor,
              seenToolCalls,
              transcript: this.transcript,
              events,
              signal,
            }),
          )
          if (toolOutcome.awaitingInput) state.awaitingInput = true

          state.toolsRan = true

          if (signal?.aborted) {
            log.info('agent', 'Agent run aborted after tool execution')
            break
          }
          continue
        }

        // No tool calls — walk the recovery rules (truncation continuation, stranded tool
        // call, the two empty-response shapes). The rules and their rationale live in
        // ./recovery.ts; at most one fires per turn.
        const recovery = attemptRecovery(response, state, this.context, recoveryCaps)
        if (recovery.action === 'retry') continue
        if (recovery.action === 'abort') {
          finalContent = recovery.finalContent
          addMessage(this.context, { role: 'assistant', content: finalContent })
          break
        }

        // Recovery exhausted but markup still present: strip it rather than print raw XML
        // as the reply. The note says a call was dropped; the broken JSON helps nobody.
        const finalPiece = hasStrandedToolCall(response.content)
          ? stripStrandedToolCalls(response.content)
          : response.content

        finalContent = state.accumulatedContent + finalPiece
        addMessage(this.context, { role: 'assistant', content: finalPiece })

        if (events?.onPostResponseValidation && !state.validationRetried) {
          const validation = await events.onPostResponseValidation(finalContent)
          if (!validation.valid) {
            state.validationRetried = true
            const feedback = validation.feedback ?? DEFAULT_VALIDATION_FEEDBACK
            log.info('agent', `Post-response validation failed: ${feedback.slice(0, 100)}`)
            addMessage(this.context, { role: 'user', content: validationFailedNudge(feedback) })
            state.accumulatedContent = ''
            state.continuationRetries = 0
            continue
          }
        }

        events?.onResponseComplete?.()

        if (isPlanning) {
          isPlanning = false
          return {
            content: finalContent,
            provider: provider.name,
            usage: totalUsage,
            turns: state.turns,
            isPlan: true,
            thinking: lastThinking,
          }
        }

        break
      }

      if (state.turns >= maxTurns && !finalContent && !signal?.aborted) {
        if (options.unbounded) {
          // The safety ceiling is not a normal exit: a healthy unbounded run ends on a
          // failure detector or its own conclusion. Reaching it means one didn't fire.
          log.error(
            'agent',
            `Unbounded run hit the ${UNBOUNDED_SAFETY_CEILING}-turn safety ceiling — a failure detector should have stopped it sooner`,
          )
        } else {
          log.warn('agent', `Exhausted max turns (${maxTurns}) without a final response`)
        }
        finalContent = await this.forceFinalResponse(totalUsage, thinking, events, signal)
        events?.onResponseComplete?.()
      }

      this.maybeRunAutoExtraction()

      return {
        content: finalContent,
        provider: provider.name,
        usage: totalUsage,
        turns: state.turns,
        thinking: lastThinking,
        continuationRetries: state.continuationRetries > 0 ? state.continuationRetries : undefined,
        aborted: signal?.aborted ? true : undefined,
        awaitingInput: state.awaitingInput ? true : undefined,
      }
    } finally {
      this.activeRun = null
      externalSignal?.removeEventListener('abort', forwardAbort)
      this.history.persistNew(this.context.messages)
      this.transcript?.turnEnd(this.context.sessionId, {
        content_length: finalContent.length,
        provider: provider.name,
        input_tokens: totalUsage.input_tokens,
        output_tokens: totalUsage.output_tokens,
        turns: state.turns,
        duration_ms: Date.now() - turnStartedAt,
      })
    }
  }

  /**
   * Force a final text response after max turns are exhausted mid-tool-flow.
   * Runs one extra inference with no tools so the model summarizes where it
   * got to, instead of returning a stale assistant message from history.
   */
  private async forceFinalResponse(
    totalUsage: { input_tokens: number; output_tokens: number },
    thinking?: ThinkingConfig,
    events?: AgentEventHandler,
    signal?: AbortSignal,
  ): Promise<string> {
    addMessage(this.context, { role: 'user', content: MAX_TURNS_SUMMARY_NUDGE })

    try {
      const result = await chatWithContextWindow({
        provider: this.localProvider,
        systemPrompt: this.context.systemPrompt,
        messages: this.context.messages,
        conversationSummary: this.context.conversationSummary,
        tools: [],
        contextLength: this.config.local.contextLength,
        tokenizer: this.tokenizer,
        cacheSlot: this.cacheSlot(),
        onToken: events?.onToken,
        onThinkingToken: events?.onThinkingToken,
        thinking,
        signal,
      })

      totalUsage.input_tokens += result.response.usage.input_tokens
      totalUsage.output_tokens += result.response.usage.output_tokens

      const content = result.response.content.trim()
      if (content) {
        addMessage(this.context, { role: 'assistant', content: result.response.content })
        return result.response.content
      }
    } catch (error) {
      log.warn('agent', 'Forced final response failed:', error)
    }

    return '[Agent reached maximum turns without producing a final response]'
  }

  private scheduleCompaction(droppedMessages: ChatMessage[]): void {
    this.compactor.schedule({
      droppedMessages,
      context: this.context,
      history: this.history,
      provider: this.auxProvider,
      memory: this.memory,
      conversationStore: this.conversationStore,
    })
  }

  private maybeRunAutoExtraction(): void {
    if (!this.memory || !this.config.memory.autoExtract) return

    const newMessages = this.history.takeUnextracted(this.context.messages)
    if (newMessages.length === 0) return

    runAutoExtraction({
      messages: newMessages,
      provider: this.auxProvider,
      memory: this.memory,
      sessionId: this.context.sessionId,
      minMessages: this.config.memory.extractionMinMessages,
      maxExtractions: this.config.memory.extractionMaxPerTurn,
    })
  }

  getContext(): AgentContext {
    return this.context
  }

  /** Get a snapshot of the current context window usage */
  contextStatus(): Promise<ContextStatus> {
    return computeContextStatus(this.config, this.tokenizer, this.context)
  }

  /** Manually trigger context compaction on the current conversation */
  async compactNow(): Promise<{ messagesBefore: number; messagesAfter: number }> {
    await this.compactor.drain()

    const messagesBefore = this.context.messages.length
    if (messagesBefore < 4) {
      return { messagesBefore, messagesAfter: messagesBefore }
    }

    const keepCount = 4
    const dropCount = messagesBefore - keepCount
    const droppedMessages = this.context.messages.slice(0, dropCount)
    const keptMessages = this.context.messages.slice(dropCount)

    this.scheduleCompaction(droppedMessages)

    this.context.messages = keptMessages
    this.history.replaceAll(keptMessages)

    return { messagesBefore, messagesAfter: keptMessages.length }
  }

  clearContext(): void {
    this.context = createAgentContext(this.config, this.context.sessionId, this.promptOptions)
    this.history.reset()
    this.compactor.reset()
  }

  resetSession(): void {
    this.history.deleteStored()
    this.clearContext()
  }
}

export function createAgentLoop(deps: AgentLoopDeps): AgentLoop {
  return new AgentLoop({
    ...deps,
    sessionId: deps.sessionId ?? crypto.randomUUID(),
  })
}
